BackEnd/BackEnd/Models/Banner.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BackEnd.Models
{
    public class Banner
    {
        public int Id { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        public string Description { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }


    }
}

BackEnd/BackEnd/Areas/AdminPanel/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BackEnd.DAL;
using BackEnd.Extensions;
using BackEnd.Helpers;
using BackEnd.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace BackEnd.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class BannerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public BannerController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            Banner banner = _context.Banners.FirstOrDefault();
            return View(banner);
        }

        public IActionResult Update(int? id)
        {
            Banner banner = _context.Banners.FirstOrDefault(a => a.Id == id);
            return View(banner);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Banner banner)
        {
            Banner bannerOld = _context.Banners.FirstOrDefault(a => a.Id == id);
            if (id == null) return NotFound();
            if (banner == null) return NotFound();

            if (banner.Photo != null)
            {
                if (!banner.Photo.IsImage())
                {
                    ModelState.AddModelError("Photos", $"{banner.Photo.FileName} - not image type");
                    return View(bannerOld);
                }

                string folder = Path.Combine("img", "banner");
                string fileName = await banner.Photo.SaveImageAsync(_env.WebRootPath, folder);
                if (fileName == null)
                {
                    return Content("Error");
                }

                Helper.DeleteImage(_env.WebRootPath, folder, bannerOld.Image);
                bannerOld.Image = fileName;
            }


            bannerOld.Description = banner.Description;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

BackEnd/BackEnd/Areas/AdminPanel/Views/Banner/Index.cshtml
@model Banner
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <table class="table table-striped table-light">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Description</th>
                <th scope="col">Settings</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img width="200" style="width:200px !important;height:200px !important" src="~/img/banner/@Model.Image" /></td>
                <td>@Html.Raw(Model.Description)</td>
                <td>
                </td>

            </tr>
        </tbody>
    </table>
    <div class="row justify-content-center mt-4">
        <a class="btn btn-pinterest" asp-controller="Banner" asp-action="Update" asp-route-id="@Model.Id">Update</a>
    </div>
</div>

BackEnd/BackEnd/Areas/AdminPanel/Views/Banner/Update.cshtml
@model Banner
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>
<div class="container bg-white p-5">
    <div class="row">
        <div class="col-md-12 ">
            <form method="post" enctype="multipart/form-data">
                <div class="col-md-8 offset-md-2 mb-3">
                    <img src="~/img/banner/@Model.Image" alt="Alternate Text" />
                </div>


                <div class="form-row">
                    <div class="form-group col-md-8 offset-md-2">
                        <label asp-for="@Model.Description">Description</label>
                        <textarea asp-for="@Model.Description"></textarea>
                        <span class="text-danger" asp-validation-for="@Model.Description"></span>
                    </div>
                </div>

                <div class="text-center">
                    <h3 class="mb-3">Add Image</h3>
                    <div class="row align-items-center bg-light">
                        <div class="col-md-8">
                            <div class="custom-file my-3">
                                <input asp-for="@Model.Photo" class="custom-file-input">
                                <label asp-for="@Model.Photo" class="custom-file-label">Choose file</label>
                                <span asp-validation-for="@Model.Photo" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <img height="200" width="200" class="image-preview img-fluid my-4" />
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success">Update</button>
                    <a asp-action="Index" class="btn btn-info">Close</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.ckeditor.com/ckeditor5/23.1.0/classic/ckeditor.js"></script>
<script>

    ClassicEditor
        .create(document.querySelector('#Description'))
        .catch(error => {
            console.error(error);
        });
</script>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#Photo").change(function () {
            var file = this.files[0];
            var fileReader = new FileReader();
            fileReader.onload = function (e) {
                $(".image-preview").attr("src", e.target.result);
            };
            fileReader.readAsDataURL(file, "UTF-8");
        });
    });
</script>

@section Scripts{
    <partial name="_Validation" />

}