BackEnd/BackEnd/Controllers/FavoriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BackEnd.DAL;
using BackEnd.Models;
using BackEnd.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BackEnd.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly AppDbContext _context;
        public FavoriteController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<FavoriteVM> dbBasket = new List<FavoriteVM>();
            ViewBag.Total = 0;
            if (Request.Cookies["favorite"] != null)
            {

                List<FavoriteVM> favorite = JsonConvert.DeserializeObject<List<FavoriteVM>>(Request.Cookies["favorite"]);

                foreach (FavoriteVM pro in favorite)
                {
                    Product dbProduct = await _context.Products.FindAsync(pro.Id);
                    pro.Price = dbProduct.Price;
                    pro.Image = dbProduct.Image;
                    pro.New = dbProduct.New;
                    dbBasket.Add(pro);
                    ViewBag.Total += pro.Price;
                }
            }



            return View(dbBasket);
        }
        public async Task<IActionResult> AddFavorite(int? id)
        {
            if (id == 0) return NotFound();
            Product product = await _context.Products.FirstOrDefaultAsync(c => c.Id == id);
            if (product == null) return NotFound();
            List<FavoriteVM> favorite;
            if (Request.Cookies["favorite"] != null)
            {
                favorite = JsonConvert.DeserializeObject<List<FavoriteVM>>(Request.Cookies["favorite"]);
            }
            else
            {
                favorite = new List<FavoriteVM>();
            }
            FavoriteVM isExist = favorite.FirstOrDefault(p => p.Id == id);
            if (isExist == null)
            {
                favorite.Add(new FavoriteVM
                {
                    Id = (int)id,
                    Count = 1
                });
            }
            else
            {
                isExist.Count += 1;
            }

            Response.Cookies.Append("favorite", JsonConvert.SerializeObject(favorite));
            return RedirectToAction(nameof(Index));

        }

       
    }
}

BackEnd/BackEnd/Views/Favorite/Index.cshtml
@model List<FavoriteVM>
@{
    ViewData["Title"] = "Index";
    int count = Model.Count();
}
<!-- MAIN START -->
<main>
    <section id="heading">
        <div class="heading-banner-area overlay-bg"
             style="
            background-image: url(img/bg/1.jpg);
            background-position: center;
            background-repeat: no-repeat;
          ">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="heading-banner">
                            <div class="heading-banner-title">
                                <h2>My Favorite</h2>
                            </div>
                            <div class="breadcumbs pb-15">
                                <ul>
                                    <li class="home"><a asp-controller="Home" asp-action="Index">Home</a></li>
                                    <li>My Favorite</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--SECTION PURCHASE AREA START-->
    <section id="purchase" class="padding-100" style="overflow: hidden">
        <div class="container">
            <!-- Section-title start -->
            @if (count != 0)
            {
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title text-center">
                            <h2 class="title-center">My Favorite Furnitures</h2>
                        </div>
                    </div>

                    <!-- Section-title end -->
                    <div class="col-lg-12">
                        <div class="row">
                            @foreach (FavoriteVM product in Model)
                            {
                                <!-- SECTION ITEM START -->
                                <div class="col-lg-3">
                                    <div class="items">
                                        <div class="card">
                                            <div class="img-box">
                                                <span class="pro-label new-label">@product.New</span>
                                                <span class="pro-price-2 pro-price-1">$ @product.Price</span>
                                                <img src="img/product/@product.Image" alt="" />
                                            </div>
                                            <div class="card-content p-2">
                                                <h4 class="mt-3 mb-3"><a asp-controller="Product" asp-action="Detail" asp-route-id="@product.Id">@product.Name</a></h4>
                                                @*<div class="fix">
                                                <span class="pro-rating">
                                                    @if (product.Rate > 5)
                                                    {
                                                        product.Rate = 5;
                                                    }

                                                    @for (int i = 1; i <= 5; i++)
                                                    {
                                                        <a class='rating-@(i<=product.Rate?"on":"off")'><i class="fas fa-star"></i></a>

                                                    }
                                                </span>
                                            </div>*@
                                                <div class="product-action">
                                                    <a asp-controller="Favorite" asp-action="AddFavorite" asp-route-id="@product.Id"
                                                       title="Wishlist">
                                                        <i class="far fa-heart"></i>
                                                    </a>
                                                    <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id"
                                                       title="Quick View">
                                                        <i class="fas fa-shopping-cart"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- SECTION ITEM END -->
                            }
                        </div>
                    </div>


                </div>
            }
            else
            {
                <div class="col-lg-12 text-center">
                    <h2>Sebet bosdur,<a asp-controller="Product" asp-action="Index">Buyurun mehsullara baxin</a></h2>
                </div>
            }
        </div>
    </section>
    <!--SECTION PURCHASE AREA END-->
</main>
<!-- MAIN END -->